name: Notice i18n Tasks
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    paths:
    - hoge/*

jobs:
  notice-i18n-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name : Check the diffs when the issue is opened
        id: diff-check-opened
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        run: echo "diff-count=1" >> $GITHUB_OUTPUT

      - name: Check the diffs when the content in the PR updated
        id: diff-check-updated
        if: github.event.action == 'synchronize'
        run: echo "diff-count=$(git diff ${{ github.event.before }} ${{ github.event.after }} --name-only --relative=hoge | wc -l)" >> $GITHUB_OUTPUT

      - name: Send notice on the issue
        uses: actions/github-script@v6
        if: steps.diff-check-opened.outputs.diff-count > 0 || steps.diff-check-updated.outputs.diff-count > 0
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `改行は
                できるかな？
                ## MDは
                どうかな？`,
            })
