name: Notice i18n Tasks
on:
  pull_request_target:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  notice-i18n-tasks:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
    - name: Debug
      run: |
        echo "github.ref: ${{ github.ref }}"
        echo "github.head_ref: ${{ github.head_ref }}"
        echo "github.base_ref: ${{ github.base_ref }}"
        echo "github.event.pull_requests.head.ref: ${{ github.event.pull_request.head.ref }}"
        echo "github.event.pull_request.head.repo.full_name: ${{ github.event.pull_request.head.repo.full_name }}"
        echo "github.sha: ${{ github.sha }}"
        echo "github.event.before: ${{ github.event.before }}"
        echo "github.event.after: ${{ github.event.after }}"

    - name: Check out
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Debug 2
      run: |
        git log --oneline --no-abbrev-commit

    - name: Check diffs
      id: check-diffs
      run: |
        echo "diff-count=$(.github/workflows/deep-diff.sh hoge ${{ github.sha }} ${{ github.event.after }} | wc -l)" >> $GITHUB_OUTPUT

    - name: Send notice on the issue
      if: steps.check-diffs.outputs.diff-count > 0
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: execution
        message: |
          github.sha: ${{ github.sha }}
          github.event.after: ${{ github.event.after }}
          ### Action Required
          You are adding or updating English content so please take the following actions for other languages.
          - If you add new content under `website/content/en` or targets of the symbolic links in the same directory, please replicate it in the corresponding directories of all other languages. (e.g. If you create `website/content/en/blog/new-post.md`, you should copy it to `website/content/ja/blog/new-post.md`, etc.)
          - If you update the content in the same location, please perform the following actions for the corresponding content in other languages.
            - If the content has not been translated yet, replace the files with the updated English version.
            - If the content has already been translated, include a note suggesting that users check the English page for the most recent updates.

