name: Notice i18n Tasks
on:
  pull_request_target:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  notice-i18n-tasks:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Check diffs
      id: check-diffs
      run: |
        updated_files="$(.github/workflows/deep-diff.sh hoge ${{ github.sha }} ${{ github.event.pull_request.head.sha }})"
        echo "count=$(echo $updated_files | grep -v '^$' | wc -l)" >> $GITHUB_OUTPUT

    - name: Send notice on the issue
      if: steps.check-diffs.outputs.count > 0
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: i18n-notice
        message: |
          github.sha: ${{ github.sha }}
          github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}
          ### Action Required
          You are adding or updating English content so please take the following actions for other languages.
          - If you add new content under `website/content/en` or targets of the symbolic links in the same directory, please replicate it in the corresponding directories of all other languages. (e.g. If you create `website/content/en/blog/new-post.md`, you should copy it to `website/content/ja/blog/new-post.md`, etc.)
          - If you update the content in the same location, please perform the following actions for the corresponding content in other languages.
            - If the content has not been translated yet, replace the files with the updated English version.
            - If the content has already been translated, include a note suggesting that users check the English page for the most recent updates.

